### ISSUE TITLE
Grunt file

### ISSUE THREAD

**Issue by aleray** [FremyCompany/css-regions-polyfill#19]
Hi,

What is the procedure to build the dist files? Are you using Grunt? Could you give me some hints to build myself the files?

thanks,

Alex

**Comment by FremyCompany** [comment]
To install: 
- Install grunt
- Open a command line on the repository folder & run "npm install"

To build:
- Open a command line on the repository folder & run "grunt

This should do the trick. If it doesn't, please tell me what happens on your side.

**Comment by aleray** [comment]
Hi and thanks for your answer,

so basically I install grunt via `npm install grunt` and then run `grunt`? It seems like the gruntfile is missing:

    Fatal error: Unable to find Gruntfile.

Thanks,

**Comment by FremyCompany** [comment]
Oops, you're right obviously :D
They should be the same as in https://github.com/FremyCompany/css-grid-polyfill.

The issue is that, for some reason, I added "package.json" and "gruntfile.js" to the ".gitignore" so they are not sent to the repository. My bad. I'll fix that once I'm at home.

Thanks for the catch,
François

**Comment by FremyCompany** [comment]
To my own disappointment, I noticed I never published the version of css-regions-polyfill relying on the new internals of css-grid-polyfill. That means there was probably some bug I didn't work out at the time. I'll have another look at it this week-end, but in the mean time I included the current grunt files.

Best regards,
François

**Comment by aleray** [comment]
Thanks!
