### ISSUE TITLE
Last break-after not working

### ISSUE THREAD

**Issue by tlechauve** [FremyCompany/css-regions-polyfill#25]
Hi, me again,

During some tests, i wrote this code http://codepen.io/anon/pen/VvbzOr and the results is quite strange. The last break-after is not applied whatever the number of regions.

Any ideas ?

**Comment by FremyCompany** [comment]
Hi,

Thanks for the bug report. I can confirm I see this issue here.

I'm currently in the process of relocating to Seattle so I may not have much time to spend on this issue but I suspect this must lie in the extractOverflowingContent code. There's some code there that tries to take forced breaks into consideration, and for some reason it does not run on the before-last split, which is interesting.

My wild guess is that the whole content is actually fitting in the region so the code detects no break are required to fit the region and therfore does not apply the forced break fix, since no fragmentation is initiated.

EDIT: This hypothesis was confirmed by changing the height of the regions to 300px. In that case, no breaking happen at all. If you want to attempt a fix, I can point you in the right direction. Otherwise you may have to wait a bit before I can get free time to work on this, as I have already a few things before this.

**Comment by FremyCompany** [comment]
https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/css-regions/polyfill.js#L126 is where one should start to investigate the issue

**Comment by tlechauve** [comment]
Finally i resolved this issue replacing
```
#elements {
  flow-into: flowbox contents;
}
```
by
```
#elements {
  flow-into: flowbox content;
}
```

Try it : http://codepen.io/anon/pen/NGaNYe
