### ISSUE TITLE
Missing special-continued-fragment?

### ISSUE THREAD

**Issue by RonaldTreur** [FremyCompany/css-regions-polyfill#47]
Upon studying this polyfill's code, I stumbled upon this interesting tidbit:

https://github.com/FremyCompany/css-regions-polyfill/blob/f508484fbe5d4f208c3592a4e71e729e06582169/src/css-regions/polyfill.js#L671-L690

These 4 conditionals perform more or less the same logic, but line 683 deviates from its equivalent in the other three conditionals:
https://github.com/FremyCompany/css-regions-polyfill/blob/f508484fbe5d4f208c3592a4e71e729e06582169/src/css-regions/polyfill.js#L683

Compared to (for example) line 688:
https://github.com/FremyCompany/css-regions-polyfill/blob/f508484fbe5d4f208c3592a4e71e729e06582169/src/css-regions/polyfill.js#L688

it lacks the "special"-part in the name of the assigned attribute. I am pretty sure this was not intended, given that the attribute that is now set, was purposely removed on the previous line (682).

Admittedly I have not encountered any issues due to this and I have not tried to produce one. Though it's been a few years, I am hoping @FremyCompany is able to verify that this is indeed an omission.

**Comment by FremyCompany** [comment]
Hi @RonaldTreur!

Sorry for my lack of reactiviy, I just noticed all the notifications on the project.

The typo (because it is indeed a typo) meant that in the (almost impossible) case where a bottom border was spliced across regions, the ::after pseudo element would be unduly hidden in the fragment before the border split.

I will accept you pull request, thanks for taking a look!
